update description and links
spdx/LicenseListPublisher pull request #89
Opened 2020-11-25 01:28 UTC by jlovejoy

update description and links to be current

2020-11-25 01:28 UTC, jlovejoy commented
@swinslow - please have a look!

2020-11-28 17:45 UTC, swinslow requested changes
Hi @jlovejoy, the substance of this looks good to me. There are a few necessary formatting edits (missing closing `</a>` tags to be added and possibly an extra `</ul>` tag to be deleted), and a few less-necessary recommended edits to update URLs. 

I'm making changes to the version that I'm implementing on the live site for the 3.11 release to address these comments, and I will circle back to update them in this PR -- or feel free to make the edits here yourself if you have time. Thanks!

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/ExceptionsTocHTMLTemplate.html
> +      </ul>
I think this additional `</ul>` is duplicative and shouldn't be added, unless I'm misreading?

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/ExceptionsTocHTMLTemplate.html
> +	      <li style="margin:0px 0 5px 10px;">Use <a href="http://spdx.org/ids"><strong>short identifiers in your source code</strong></a></li>
The URL here can be updated to https://spdx.dev/ids

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/ExceptionsTocHTMLTemplate.html
> +            <li style="margin:5px 0 5px 10px;">The <a href="http://spdx.org/spdx-license-list/matching-guidelines"><strong>matching guidelines</strong></a> define what constitutes a license or except
The URL here can be updated to https://spdx.dev/license-list/matching-guidelines/

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/TocHTMLTemplate.html
> +	      <li style="margin:0px 0 5px 10px;">Use <a href="http://spdx.org/ids"><strong>short identifiers in your source code</strong></a></li>
The URL can be updated to https://spdx.dev/ids

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/TocHTMLTemplate.html
> +            <li style="margin:5px 0 5px 10px;">The <a href="http://spdx.org/spdx-license-list/matching-guidelines"><strong>matching guidelines</strong></a> define what constitutes a license or except
The URL can be updated to https://spdx.dev/license-list/matching-guidelines/

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/TocHTMLTemplate.html
> +            <li style="margin:5px 0 5px 10px;"><a href="./exceptions-index.html"><strong>License Exceptions</strong></a> are commonly found exceptions to free and open source licenses, used with the
The second URL (for the specifications link) can be updated to https://spdx.dev/specifications/

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/TocHTMLTemplate.html
> +	      <li style="margin:5px 0 5px 10px;"><a href="https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md"><strong>Explanation of fields</strong> used on the SPDX License List</l
Here and below, some of the links are missing the closing `</a>` tag outside the closing `</strong>` tag.

2020-11-28 17:45 UTC, swinslow commented on resources/htmlTemplate/ExceptionsTocHTMLTemplate.html
> +	      <li style="margin:5px 0 5px 10px;"><a href="https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md"><strong>Explanation of fields</strong> used on the SPDX License List</l
Here and below, some of the links are missing the closing `</a>` tag outside the closing `</strong>` tag.

2021-02-05 19:19 UTC, goneall commented
@jlovejoy @swinslow There is a change request on this PR - if you could review/update I can merge in the changes before the next license list release.

2021-02-18 16:40 UTC, swinslow approved these changes

2021-02-18 16:40 UTC, swinslow commented
Thanks @goneall, I've pushed the changes to fix the issues I flagged above -- should be good to go now.

2021-02-18 18:21 UTC, goneall commented
Thanks @swinslow !

2021-02-18 18:21 UTC, merged